### PR TITLE
Insource external shim.min.js file

### PR DESCRIPTION
**Pull request by andreas-hauser**
Insource external shim.min.js file (necessary for the Peregrine editor to work in IE) as described in issue #196. Usage of the insourced shim.min.js file for the available sample pages is also added.

### CODE REVIEW

**Comment by reusr1** [comment]
hey, thank you for this PR - unfortunately we do have to change the approach on this a bit. The page renderer should not rely on the admin console as the admin console may not be necessary on some instance types (say a server only serving a site and not the admin console). It would also be good to pull the shim from the npm repo instead of just copying it into the project.

**Comment by andreas-hauser** [comment]
@reusr1 
as the file is only needed by IE, is there a good way of importing it from the npm repo only when necessary?

**Comment by reusr1** [comment]
@andreas-hauser - have a look at the maven pom file @ https://github.com/headwirecom/peregrine-cms/blob/develop/pagerenderer/vue/ui.apps/pom.xml - this instructs maven to copy the files to the final package that is installed in peregrine. The shim should be added to that list but needs to go into a different folder in order to not be included in the combined js file. The reference to the file from the page components can then stay the same, just insourced.

**Comment by andreas-hauser** [comment]
@reusr1 
the shim has been moved into the pagerenderer module and it's included in the new conditional-js folder.

**Pull request merged**
