### PR TITLE
Feature/firstlogin

### PR DESCRIPTION
**Pull request by reusr1**
- a basic implementation of an accept terms and conditions screen
- frontend implementation only, can be circumvented at this point

### CODE REVIEW

**Comment by reusr1** [comment]
if we want to implement backend security for this feature as well we should do this by adding a group to the user when the terms and conditions are accepted.

**Review by GastonGonzalez — APPROVED** [review]
@reusr1 , outside of your "TODOs" this PR looks good. I corrected a couple of grammatical issues in the flow and added some error logging.

**Comment by GastonGonzalez** [comment]
@reusr1 - A swagger update is needed given the new endpoint.

**Comment by reusr1** [comment]
closing PR as this was merged into feature/tenantstate

**Pull request closed without merging**
