### PR TITLE
feature/ignore-container-components

### PR DESCRIPTION
**Pull request by flx-sta**
### Feature
This feature adds a new button to the left of the preview button which, when active, makes it impossible to hover/click on container-elements in the editor.
The feature does disable itself when a new component is being dragged from the right panel (dragStart) and reactivates itself after the component has been dropped (if it was active before, basically return to its desired state).

Screenshot 2019-05-27 at 13 22 09
Screenshot 2019-05-27 at 13 25 21

_This is useful for more complex templates/pages where you might want to select an element inside a couple of container elements and makes it easier to "hit" it with the cursor_

### CODE REVIEW

**Comment by flx-sta** [comment]
I've added a fix for a error that appeared in the editor in the initial state

Additionally I've resolved the existing conflicts

**Comment by reusr1** [comment]
@bkheadwire please review and run the e2e tests to see if the PR has any impact

**Comment by bkheadwire** [comment]
@reusr1 PR has no impact on e2e tests.

**Comment by bkheadwire** [comment]
The interaction between the ignore-containers mode and preview mode is a bit awkward: https://youtu.be/O4y-CfKfQzM

Probably shouldn't be able to enter ignore-containers mode while preview is active, and definitely should have the state match the button mode when switching back to editing.

**Comment by flx-sta** [comment]
> The interaction between the ignore-containers mode and preview mode is a bit awkward: https://youtu.be/O4y-CfKfQzM
> 
> Probably shouldn't be able to enter ignore-containers mode while preview is active, and definitely should have the state match the button mode when switching back to editing.

You are right.
I've missed that bug, I'll create a Ticket to fix it on our board
The buttons does actually match the current state, but that bugs "destroys" the construct.

Heres why:

There is 3 states: enabled, disabled & on-hold
Whenever a new component is in dragging oder the preview mode was switch while ignoreContainer was "enabled" the state is automatically changed to "on-hold". 
This means, the very moment the dragging ends or the very moment the preview mode is switched off again it automatically reactivates itself.

**Comment by flx-sta** [comment]
> The interaction between the ignore-containers mode and preview mode is a bit awkward: https://youtu.be/O4y-CfKfQzM

### I've fixed the given issue now

**Comment by flx-sta** [comment]
@reusr1 I think there is a problem with travis here.

**Pull request merged**
