### PR TITLE
Issues/559 update

### LINKED ISSUE #559: 'Unpublish' does not work for page / object / template
When an author tries to unpublish a page / object / template, the process does not succeed.  
There is also no visual indication of the process in progress.

**Branch**: [develop-sling12](https://github.com/headwirecom/peregrine-cms/pull/508)

## Steps to Reproduce
1. Grab a new peregrine instance with e.g. themeclean-flex theme installed.
1. Create new website _A_.
1. Create a page / object / template.
1. Replicate it.
1. Unpublish it.
1. Check `staticreplication` directory.

**Expected Result**: There is some progress information.  The unpublished resources are not cached anymore.
**Actual Result**: We don't know that the process is running. The resources were not removed from the replication cache.

### LINKED ISSUE #568: Exceptions on develop-sling12 peregrine startup
These are Exceptions that I get when running `java -agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=n -jar org.apache.sling.feature.launcher.jar -f com.peregrine-cms.sling.launchpad-12-SNAPSHOT-oak_tar_fds_far.far -D sling.runmodes=author,notshared,oak_tar_fds -p sling` on Windows with the branch [develop-sling12](https://github.com/headwirecom/peregrine-cms/tree/develop-sling12):
```W:\headwire\PeregrineCMS\percms\12>java -agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=n -jar org.apache.sling.feature.launcher.jar -f com.peregrine-cms.sling.launchpad-12-SNAPSHOT-oak_tar_fds_far.far -D sling.runmodes=author,notshared,oak_tar_fds -p sling
Listening for transport dt_socket at address: 8001
[INFO]
[INFO] Apache Sling Application Launcher
[INFO] ---------------------------------
[INFO] Initializing...
[INFO] Artifact Repositories: [file:///C:/Users/reggi/.m2/repository, https://repo.maven.apache.org/maven2, https://repository.apache.org/content/groups/snapshots]
[INFO] Assembling provisioning model...
[INFO]
[INFO] Assembling launcher...
[INFO] Using 365 local artifacts, 0 cached artifacts, and 0 downloaded artifacts
[INFO]
[INFO] Starting launcher...
[INFO] Launcher Home: W:\headwire\PeregrineCMS\percms\12\sling
[INFO] Cache Directory: W:\headwire\PeregrineCMS\percms\12\launcher\cache
[INFO]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/C:/Users/reggi/.m2/repository/org/apache/felix/org.apache.felix.
framework/6.0.3/org.apache.felix.framework-6.0.3.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Started Jetty 9.4.28.v20200408 at port(s) HTTP:8080 on context path / [minThreads=8,maxThreads=200,acceptors=1,selectors=4]
[INFO] Apachde Felix Http Whiteboard Service started
ERROR: bundle org.apache.sling.settings:1.4.0 (22)[org.apache.sling.settings.impl.SlingPropertiesPrinter(1)] :  Error during instantiation of the implementation object
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.felix.scr.impl.inject.internal.ComponentConstructorImpl.newInstance(ComponentConstructorImpl.java:312)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:279)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:984)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:957)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:902)
        at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:348)
        at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:248)
        at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:350)
        at org.apache.felix.framework.Felix.getService(Felix.java:3954)
        at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:450)
        at org.apache.felix.inventory.impl.webconsole.WebConsoleAdapter.addingService(WebConsoleAdapter.java:152)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:871)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264)
        at org.apache.felix.inventory.impl.webconsole.WebConsoleAdapter.<init>(WebConsoleAdapter.java:68)
        at org.apache.felix.inventory.impl.Activator.start(Activator.java:63)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: No bundle context property 'sling.properties.url' provided
        at org.apache.sling.settings.impl.SlingPropertiesPrinter.<init>(SlingPropertiesPrinter.java:64)
        ... 30 more
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Storing Memory Dumps in W:\headwire\PeregrineCMS\percms\12\sling\framework\bundle54\data\dumps
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Setting Automatic Memory Dump Threshold to 0% for pools [CodeHeap 'non-nmethods', CodeHeap 'non-profiled nmethods', CodeHeap 'profi
led nmethods', Compressed Class Space, G1 Old Gen, Metaspace]
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Automatic Memory Dump cannot be set for pools [G1 Eden Space, G1 Survivor Space]
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Setting Automatic Memory Dump Interval to 21600 seconds
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Setting Automatic Memory Dump Threshold to 0% for pools [CodeHeap 'non-nmethods', CodeHeap 'non-profiled nmethods', CodeHeap 'profi
led nmethods', Compressed Class Space, G1 Old Gen, Metaspace]
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Automatic Memory Dump cannot be set for pools [G1 Eden Space, G1 Survivor Space]
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Setting Automatic Memory Dump Interval to 21600 seconds
INFO : org.apache.felix.webconsole.plugins.memoryusage (54): Storing Memory Dumps in W:\headwire\PeregrineCMS\percms\12\sling\framework\bundle54\data\dumps
wrz 23, 2020 2:02:37 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: TIFFImageWriter not loaded. tiff files will not be processed
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

wrz 23, 2020 2:02:37 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
[DEBUG] [ServiceReference 421 from bundle 103 : org.apache.sling.jcr.davex:1.3.10 ref=[javax.servlet.Servlet] properties={objectClass=[javax.servlet.Servlet], osgi.http.whiteboard.context.sele
ct=(osgi.http.whiteboard.context.name=DavExAuthHttpContext), osgi.http.whiteboard.servlet.pattern=/server/*, service.bundleid=103, service.description=Sling JcrRemoting Servlet, service.id=421
, service.scope=singleton, service.vendor=The Apache Software Foundation, servlet.init.createAbsoluteURI=true, servlet.init.csrf-protection=disabled, servlet.init.protectedhandlers-config=org.
apache.jackrabbit.server.remoting.davex.AclRemoveHandler, servlet.init.resource-path-prefix=/server, sling.auth.requirements=-/server}] Ignoring unmatching Servlet service
ESAPI: WARNING: System property [org.owasp.esapi.opsteam] is not set
ESAPI: WARNING: System property [org.owasp.esapi.devteam] is not set
ESAPI: Attempting to load ESAPI.properties via file I/O.
ESAPI: Attempting to load ESAPI.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: W:\headwire\PeregrineCMS\percms\12\ESAPI.properties
ESAPI: Not found in SystemResource Directory/resourceDirectory: .esapi\ESAPI.properties
ESAPI: Not found in 'user.home' (C:\Users\reggi) directory: C:\Users\reggi\esapi\ESAPI.properties
ESAPI: Loading ESAPI.properties via file I/O failed. Exception was: java.io.FileNotFoundException
ESAPI: Attempting to load ESAPI.properties via the classpath.
ESAPI: SUCCESSFULLY LOADED ESAPI.properties via the CLASSPATH from '/ (root)' using class loader for DefaultSecurityConfiguration class!
ESAPI: SecurityConfiguration for Validator.ConfigurationFile.MultiValued not found in ESAPI.properties. Using default: false
ESAPI: Attempting to load validation.properties via file I/O.
ESAPI: Attempting to load validation.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: W:\headwire\PeregrineCMS\percms\12\validation.properties
ESAPI: Not found in SystemResource Directory/resourceDirectory: .esapi\validation.properties
ESAPI: Not found in 'user.home' (C:\Users\reggi) directory: C:\Users\reggi\esapi\validation.properties
ESAPI: Loading validation.properties via file I/O failed.
ESAPI: Attempting to load validation.properties via the classpath.
ESAPI: SUCCESSFULLY LOADED validation.properties via the CLASSPATH from '/ (root)' using class loader for DefaultSecurityConfiguration class!
Warning: Nashorn engine is planned to be removed from a future JDK release
Warning: Nashorn engine is planned to be removed from a future JDK release
Warning: Nashorn engine is planned to be removed from a future JDK release
Warning: Nashorn engine is planned to be removed from a future JDK release
Warning: Nashorn engine is planned to be removed from a future JDK release
[INFO] Framework started
23.09.2020 14:34:07.167 *INFO* [OsgiInstallerImpl] org.apache.sling.audit.osgi.installer Installed configuration org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine from resource Tas
kResource(url=jcrinstall:/apps/runmodes/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-peregrine.config, entity=config:org.apache.sling.jcr.repoinit.RepositoryInitializer~peregrine
, state=INSTALL, attributes=[org.apache.sling.installer.api.tasks.ResourceTransformer=:21:, service.factoryPid=org.apache.sling.jcr.repoinit.RepositoryInitializer, service.pid=peregrine], dige
st=c5c7279b728b00c506832d23642f265a)
23.09.2020 14:34:07.177 *INFO* [OsgiInstallerImpl] org.apache.sling.audit.osgi.installer Installed configuration org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended~peregrin
e from resource TaskResource(url=jcrinstall:/apps/runmodes/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-peregrine, entity=config:org.apache.sling.serviceuserma
pping.impl.ServiceUserMapperImpl.amended~peregrine, state=INSTALL, attributes=[org.apache.sling.installer.api.tasks.ResourceTransformer=:21:, service.factoryPid=org.apache.sling.serviceusermap
ping.impl.ServiceUserMapperImpl.amended, service.pid=peregrine], digest=e97736490720f80c1e05695b11f406ec)
ERROR: bundle com.peregrine-cms.replication.core:1.0.0.SNAPSHOT (193)[com.peregrine.admin.replication.impl.ReplicationMixinNodeTypesOverride(458)] : The activate method has thrown an exception

java.lang.IllegalArgumentException: Could not obtain Resource Resolver -> setup failed
        at com.peregrine.admin.replication.impl.ReplicationMixinNodeTypesOverride.setup(ReplicationMixinNodeTypesOverride.java:97)
        at com.peregrine.admin.replication.impl.ReplicationMixinNodeTypesOverride.activate(ReplicationMixinNodeTypesOverride.java:62)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:242)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:678)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:524)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:342)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:984)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:957)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:766)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:667)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:433)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:666)
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:353)
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:553)
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:69)
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:424)
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
        at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
        at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4817)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2336)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
        at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:97)
        at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:918)
        at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:755)
        at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:304)
        at java.base/java.lang.Thread.run(Thread.java:834)```

### PR DESCRIPTION
**Pull request by cmrockwell**
PR to fix Unpublish issue when using localFS replication

https://github.com/headwirecom/peregrine-cms/issues/559
https://github.com/headwirecom/peregrine-cms/issues/568

### CODE REVIEW

**Comment by reggie7** [comment]
Hey @cmrockwell, thanks for the PR! I took the liberty to adjust whatever I'd otherwise comment, I hope you will be fine with my changes.
But unfortunately when I checked the branch prior to my code adjustments - I saw a discrepancy from what I believe should be expected in the instance behavior. I've published a page `xyz` to get `xyz.html` and `xyz.data.json` cached in `staticreplication` container. After the **Unpublish** action - the latter got deleted while the former remained. Aren't both of them supposed to be removed? Does that work diffefently for you maybe?

**Comment by GastonGonzalez** [comment]
@cmrockwell  - Thanks for the PR. I am seeing the same issue that @reggie7 ran into abo

> Hey @cmrockwell, thanks for the PR! I took the liberty to adjust whatever I'd otherwise comment, I hope you will be fine with my changes.
> But unfortunately when I checked the branch prior to my code adjustments - I saw a discrepancy from what I believe should be expected in the instance behavior. I've published a page `xyz` to get `xyz.html` and `xyz.data.json` cached in `staticreplication` container. After the **Unpublish** action - the latter got deleted while the former remained. Aren't both of them supposed to be removed? Does that work diffefently for you maybe?

@cmrockwell - I am seeing the same issue as @reggie7. The `.html` files should be removed as well. In addition to this problem, I am seeing an issue where siblings are getting removed when the `localFS` replication service is used.

1. Configure `localFS` replication.
2. Replicate the entire set from the template settings page.
3. Unpublish a page that is in a node/folder where there is at least one another sibling page.

Actual Behavior: The page that was selected for unpublishing is unpublished with its sibiling(s). Like before, only the *.data.json files are removed. The *.html are still on the file system.

**Comment by cmrockwell** [comment]
Good catch @reggie7 @GastonGonzalez  Both issues are happening on my localFS system. I'll take a look.

**Comment by GastonGonzalez** [comment]
@cmrockwell  - Thank you for the quick fix. Your last commit (970cedf) looks good. I confirmed the following:

1. Both _page_`.data.json` and _page_`.html` are removed from the file system.
2. Siblings are no longer removed.
3. I also confirmed that removing the "author" as runmode on startup allows the `localFS` replication to be the default.

Approved and merging.

**Pull request merged**
