### PR TITLE
Fix: assets do not replicate properly (+ side quests found in the process)

### PR DESCRIPTION
**Pull request by reggie7**
Fix for #658 and many more issues with replication found in the implementation process.

All resource types (**page**, **asset**, **object**, **template**) should now allow _publish_ and _unpublish_ operations in `local FS` / `local` / `remote` replication modes (though I would need to check again whether anything was actually broken in the last one). Site Setup Replication should also work for all of them (`local` one takes forever though, I'm not fixing it here).

This issue can both be tested by technical and non-technical reviewers.

In the code review though... It seems like there is a lot of stuff, but there's actually `JUnit` coverage added here, so these are some fresh files in there. Additionally there are many changes in testing tools that were needed to prepare and simplify actual tests. So more than half of the file changes come from testing.
One can easily skip `LocalReplicationService` code review as there are strong plans to simply drop this approach at all (and I haven't written tests for it). @reusr1 would need to confirm that we drop this replication mode.
Other than that I tried to keep the changes to minimum and retract most of the unrelated cleanups, but I didn't revert all small cosmetic ones.

@cmrockwell please confirm that `remote` mode works as expected by yourself.

### CODE REVIEW

**Comment by reggie7** [comment]
@cmrockwell thanks to your fix in #831 I could myself already confirm that this PR works as expected within `remote` replication mode.

**Comment by reggie7** [comment]
I've fixed #657 and #720 in [issues/657-tenant-site-setup-replication-NPE](/headwirecom/peregrine-cms/tree/issues/657-tenant-site-setup-replication-NPE) that is based on this PR directly. Once we merge it here, I'll open the next PR.

**Review by cmrockwell — APPROVED** [review]
Nice work! I tested using: remote replication ui,  local replication ui,  ran slingjunit remote and local tests,  site setup replication, verified local assets and pages staticreplication, verified version tags are set and removed. Reviewed the code, which looks good to me.
Approved.

**Review by flx-sta — APPROVED** [review]
LGTM 🚀

**Pull request merged**
