### PR TITLE
Move replication runmodes to platform's ui.apps

### PR DESCRIPTION
**Pull request by reggie7**
Amendment to #717

### CODE REVIEW

**Review by flx-sta — CHANGES_REQUESTED** [review]
image

build fails for me. not sure if this is a personal issue only though

**Comment by reggie7** [comment]
@Felix-Puetz feels very personal indeed. I can't reproduce it. What is the system? `Windows`?

**Comment by flx-sta** [comment]
@reggie7 yes windows 10 running in bootcamp

**Comment by reggie7** [comment]
@Felix-Puetz could you check the issue again? I've checked it in my Windows machine and it works. What is the command you use?

**Review by flx-sta — APPROVED** [review]
image

**Review by reusr1 — APPROVED** [review]

**Pull request merged**
