### PR TITLE
remove old testing framework as well as deprecated sling builder

### PR DESCRIPTION
**Pull request by reusr1**
- we are not using the older testing infrasctrucure anymore
- the sling12 peregrine builder moved to its own project at https://github.com/peregrine-cms/peregrine-builder

### CODE REVIEW

**Review by reggie7 — APPROVED** [review]

**Review by flx-sta — APPROVED** [review]

**Comment by cmrockwell** [comment]
The main issue I have with this PR is that [boot.json in the replacement project](https://github.com/peregrine-cms/peregrine-builder/blob/develop/builder/src/main/features/boot.json) omits the framework properties that support runmodes as shown [line 131 and 132 as it is in the sling/peregrine-builder-sling-12 boot.json](https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/sling/peregrine-builder-sling-12/src/main/features/boot.json#L131-L132).

Many configuration use `sling:OsgiConfig` jcr:primaryType, such as those under [/apps/admin/runmodes](https://github.com/headwirecom/peregrine-cms/tree/develop-sling12/admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes)

I think that cleanup is fine, but fundamental changes that affect how configurations are applied should be done in a  separate PR.

**Comment by reusr1** [comment]
> The main issue I have with this PR is that [boot.json in the replacement project](https://github.com/peregrine-cms/peregrine-builder/blob/develop/builder/src/main/features/boot.json) omits the framework properties that support runmodes as shown [line 131 and 132 as it is in the sling/peregrine-builder-sling-12 boot.json](https://github.com/headwirecom/peregrine-cms/blob/develop-sling12/sling/peregrine-builder-sling-12/src/main/features/boot.json#L131-L132).
> 
> Many configuration use `sling:OsgiConfig` jcr:primaryType, such as those under [/apps/admin/runmodes](https://github.com/headwirecom/peregrine-cms/tree/develop-sling12/admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes)
> 
> I think that cleanup is fine, but fundamental changes that affect how configurations are applied should be done in a separate PR.

@cmrockwell thank you for spotting this - that's an oversight and needs to be addressed before we apply this PR

**Comment by reusr1** [comment]
@cmrockwell pushed a new release of the peregrine-builder that fixes the issue you raised here.

**Comment by cmrockwell** [comment]
It's still not working because of this commit
https://github.com/headwirecom/peregrine-cms/commit/6194c0188a24302f73286297d79190921fead7cf

There are tons of errors like this
26.03.2021 11:01:21.157 *ERROR* [sling-default-1-Registered Service.1398] org.apache.sling.distribution.packaging.impl.ResourceDistributionPackageCleanup Failed to get the list of packages
org.apache.sling.distribution.common.DistributionException: Failed to get the package list
	at org.apache.sling.distribution.packaging.impl.ResourceDistributionPackageBuilder.getPackages(ResourceDistributionPackageBuilder.java:259) [org.apache.sling.distribution.core:0.4.2]
	at org.apache.sling.distribution.packaging.impl.ResourceDistributionPackageCleanup.run(ResourceDistributionPackageCleanup.java:60) [org.apache.sling.distribution.core:0.4.2]
	at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:349) [org.apache.sling.commons.scheduler:2.7.12]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org.apache.sling.commons.scheduler:2.7.12]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.sling.api.resource.PersistenceException: Unable to create node at /var/sling/distribution/packages/default
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:477) [org.apache.sling.jcr.resource:3.0.22]
	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.create(AuthenticatedResourceProvider.java:182) [org.apache.sling.resourceresolver:1.7.2]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.create(ResourceResolverControl.java:381) [org.apache.sling.resourceresolver:1.7.2]
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.create(ResourceResolverImpl.java:982) [org.apache.sling.resourceresolver:1.7.2]
	at org.apache.sling.api.resource.ResourceUtil.getOrCreateResourceInternal(ResourceUtil.java:666) [org.apache.sling.api:2.23.0]
	at org.apache.sling.api.resource.ResourceUtil.getOrCreateResource(ResourceUtil.java:603) [org.apache.sling.api:2.23.0]
	at org.apache.sling.api.resource.ResourceUtil.getOrCreateResource(ResourceUtil.java:571) [org.apache.sling.api:2.23.0]
	at org.apache.sling.api.resource.ResourceUtil.getOrCreateResourceInternal(ResourceUtil.java:654) [org.apache.sling.api:2.23.0]
	at org.apache.sling.api.resource.ResourceUtil.getOrCreateResource(ResourceUtil.java:603) [org.apache.sling.api:2.23.0]
	at org.apache.sling.api.resource.ResourceUtil.getOrCreateResource(ResourceUtil.java:571) [org.apache.sling.api:2.23.0]
	at org.apache.sling.distribution.packaging.impl.DistributionPackageUtils.getPackagesRoot(DistributionPackageUtils.java:282) [org.apache.sling.distribution.core:0.4.2]
	at org.apache.sling.distribution.packaging.impl.ResourceDistributionPackageBuilder.getPackages(ResourceDistributionPackageBuilder.java:256) [org.apache.sling.distribution.core:0.4.2]
	... 6 common frames omitted


And of course the Sling Junit tests for remote use-case fail for the same reason.

**Review by cmrockwell — APPROVED** [review]

**Pull request merged**
