### PR TITLE
fix #767: show minimalistic loading animation for references

### LINKED ISSUE #767: references show old ones for a split-second
When switching to "references" tab. changing object and switch to it again you can see the references of the old entry for a split-second.

### Reproduction Steps
- create tenant
- move to `Pages`
- click on ℹ️  for `Articles` page
- switch to referneces tab on the right side
- switch to `Assets/placeholders` 
- select `man.jpg` 
- switch to the references tab
- BOOM; you see them for a sec

### PR DESCRIPTION
**Pull request by flx-sta**
image

fixes #767

### CODE REVIEW

**Review by reggie7 — APPROVED** [review]

**Review by reusr1 — CHANGES_REQUESTED** [review]
@Felix-Puetz I see a console error when clicking the parent icon on the main area of the explorer when the references screen of the 'welcome' article is shown. 

Generally I am questioning this PR a bit as it seems to lazy load the data and not load it while the page is switched as happens for the rest of the property panels.

**Review by ehdatheadwire — APPROVED** [review]
Confirmed that simple loading animation is present in the PR instance. Approved.

**Comment by flx-sta** [comment]
@reusr1 so whats your final decision on this? since i got 2 approvals

**Comment by reusr1** [comment]
> @reusr1 so whats your final decision on this? since i got 2 approvals

I stay by my comment that it seems a bit odd in the UI and a pattern we do not use anywhere else - doesntt mean we can't merge it

**Comment by flx-sta** [comment]
well we can still change/reconsider it later

**Pull request merged**
