### PR TITLE
Remove AWS replication

### PR DESCRIPTION
**Pull request by reggie7**
#705

Hide whitespaces in diff for a cleaner look (I have adjusted indentation in some pom.xml files).

### CODE REVIEW

**Comment by reggie7** [comment]
@GastonGonzalez [reminder](https://github.com/headwirecom/peregrine-cms/issues/705#issuecomment-758772959)

**Review by GastonGonzalez — APPROVED** [review]
@reggie7 - This PR looks good. Approved.

- Ran light regression in a clean Sling12 instance =>  no issues observed
- Deployed a clean Apache Karaf instance:
  - Deployed Apache Sling using the Karaf feature
  - Deployed Peregrine bundles =>All bundles now active following removal of AWS deps

Note: The test bundle still requires additional dependencies. It is still in the "Installed" state due to unsatisfied dependencies. However, these are not related to the AWS client SDK.

karaf-peregrine-bundles

**Comment by reggie7** [comment]
@GastonGonzalez thank you for your review.
The test bundle was fine in my environment. But I frequently restart the server and/or remove `sling` folder to let it start from scratch. I will maybe check this scenario on Monday with a fresh instance: 1) Deploy `develop-sling12`, 2) Deploy this branch, 3) Check the test bundle.

**Comment by GastonGonzalez** [comment]
> @GastonGonzalez thank you for your review.
> The test bundle was fine in my environment. But I frequently restart the server and/or remove `sling` folder to let it start from scratch. I will maybe check this scenario on Monday with a fresh instance: 1) Deploy `develop-sling12`, 2) Deploy this branch, 3) Check the test bundle.

@reggie7 - There is no need to go though testing on your end. The test bundle issue is only an issue in Apache Karaf. It's something that I need to fix for the Karaf integration. As far as I am concerned, this PR should be merged.

**Comment by reggie7** [comment]
It took merely a minute to just build, so I did test after all and yes, it's gotta be `Karaf` indeed.

**Comment by cmrockwell** [comment]
Note: For existing instances, the external package may need to be uninstalled using Composum.

http://localhost:8080/bin/packages.html/com.peregrine-cms/external-1.0-SNAPSHOT.zip

**Review by cmrockwell — APPROVED** [review]
Note: For existing instances, the external package may need to be uninstalled using Composum.

http://localhost:8080/bin/packages.html/com.peregrine-cms/external-1.0-SNAPSHOT.zip

**Pull request merged**
