### PR TITLE
Issues/863 allow file creation in object definitions

### LINKED ISSUE #863: "+ add object definition" doesn't allow creating schema/uischema.json
In the root of level of object definitions the button should stay as it is.

inside a object definiton the button should change its behaviour so that clicking it will end up creating a new file (e.g. `.json`).

# minimal mockup

image

### `onClick`
- opens `editFile` (hopefully vue-coremirror-lite) soon

### PR DESCRIPTION
**Pull request by flx-sta**
## Linked PRs
https://github.com/peregrine-cms/peregrine-cms-e2e-testing/pull/9´

## Screenshots
<kbd></kbd>

<kbd></kbd>

<kbd></kbd>

### CODE REVIEW

**Review by flx-sta — COMMENTED** [review]
I did a code-format on the `constants.js` file but that shouldn't be too big of an issue for th review

**Comment by reusr1** [comment]
@Felix-Puetz at this point we really only want to allow for additional ui-schemas to be created in an object definition. so I think the wizard should represent that and not be a generic file wizard. This wizard is also a departure from all the other creation wizards as it does not have a final confirm step. Since we do expect a json file to be placed we could actually reuse more of the pattern we use when creating a new object and allow for the user to add the json file right during the creation process?

Also feels to me that a name should be sufficient for the entry - don't think we need to force the user to add the json extension, right?

**Comment by flx-sta** [comment]
@reusr1 updated
image

**Comment by flx-sta** [comment]
added tests

**Review by reusr1 — APPROVED** [review]
I went ahead and made some minor changes to the labels to better reflect that we are only creating ui schemas in those folders

**Comment by reusr1** [comment]
@Felix-Puetz if you think my changes are acceptable please merge this PR

**Pull request merged**
