### PR TITLE
pathbrowser: add/upload assets on the fly (#697)

### LINKED ISSUE #697: pathbrowser: add/upload assets on the fly
Implement upload support for pathbrowser to add assets on the fly

### PR DESCRIPTION
**Pull request by flx-sta**
close #697

### CODE REVIEW

**Comment by flx-sta** [comment]
@reggie7:
> I think the refresh has a hickup in my instance:
> 
> https://user-images.githubusercontent.com/5563546/104244007-d9f1de80-5461-11eb-8305-08cdc6e0349b.mov

**Comment by flx-sta** [comment]
@reggie7 

> Other than that, as a UX side-note to @reusr1 - personally I don't fancy the `OK` button one has to click after the upload is done. I'd rather see it like this: after the upload ends we pre-select the new file. The same could happen in Assets console actually.

**Comment by flx-sta** [comment]
@Felix-Puetz 
> I'll look into the bug thanks alot.
> 
> About the user-experience: In my first scratch of this I actually made it that after finishing the upload the whole overlay would disappear. Thing is here: the upload is so fast that the overlay was barely visible. So I stuck to the known format for now but I agree that the current experience is not my favorite

**Comment by reggie7** [comment]
@Felix-Puetz thanks, the refresh issue got resolved with your latest change

**Review by ehdatheadwire — DISMISSED** [review]
Just reviewed this using a local instance for pr-701 and not seeing the refresh issue fixed. Wasn't sure if it's been fixed elsewhere and just not re-released or if I'm looking in the wrong place. Other than the refresh issue, it's looking good. 

https://user-images.githubusercontent.com/51373617/104388521-271b9200-54ee-11eb-91fe-3ddc02268661.mov

**Comment by flx-sta** [comment]
> Just reviewed this using a local instance for pr-701 and not seeing the refresh issue fixed. Wasn't sure if it's been fixed elsewhere and just not re-released or if I'm looking in the wrong place. Other than the refresh issue, it's looking good.
> 
>  [[pr701bug.mov]]

@ehdatheadwire 
Thanks for the review, I'll look into it.

----------
**Just curious what you mean with:**
> Just reviewed this using a local instance for pr-701

Meaning you checked out the branch and uploaded it to your instance?
---------
### Reproduction
Sorry @ehdatheadwire but I wasn't able to reproduct it:
image

Maybe you had an outdated version deployed. Just send me DM and we can look into it if you want

**Comment by flx-sta** [comment]
Alright I did some improvements:
* button OK is no longer enabled when still uploading (`percent < 100`)
* upon upload the last image-file is set as selected

**Review by reggie7 — APPROVED** [review]

**Comment by flx-sta** [comment]
Bugs from @reusr1 Review:

- [x] Bigger files take longer to load in the background so i looks like they aren't being displayed although the request is just still waiting. Needs a ui feedback (loading animation)
- [x] If there is 2 tenants e.g. `ruben` and `ruben42`. Upload `image.png` to `ruben`. switch to `ruben42` and upload same picture: Replace dialog comes up

**Comment by ehdatheadwire** [comment]
Yes I checked out the branch and uploaded it to my instance -- it's
probably what you stated in the ticket, that I had an outdated version.
I'll review today and see if I can reproduce. Thanks!
____________________________________________

Erin Dailey
AEM Project Lead | www.headwire.com

**Comment by flx-sta** [comment]
>  If there is 2 tenants e.g. ruben and ruben42. Upload image.png to ruben. switch to ruben42 and upload same picture: Replace dialog comes up

**Could not reproduce**

**Review by reggie7 — APPROVED** [review]

**Review by reusr1 — CHANGES_REQUESTED** [review]
- seems to have an issue with the z-order and the selection

Screenshot from 2021-01-25 15-28-26

- uplodad is not disabled in non assets mode of path browser (was able to upload an asset when editing a link on a card component

**Comment by flx-sta** [comment]
I couldnt reproduce any of the bugs you mentioned @reusr1 

fresh instance
i did merge develop-sling12 though

**Comment by reusr1** [comment]
a sample sequence producing a failure:

- update a file
- click ok
- open file browser again
- change folder
- upload same file

**Comment by flx-sta** [comment]
### Resolved some styling issues
- The overlapping `z-index`  specifically (at least current-path and the buttons overlapping)
- add small upload color-animation 
### Resolved functional issues
- when opening the upload interface the listeneres are now cleared upon closing it so no more listener stacking
    - _this was caused by some timing issues causing the listeneres to be bound to `window` but cleared from `dropContext`_

### Known Issues
- When name is already occupied clicking "keep both":
     - will not select the new asset due to not being informed of the new name 
     - might not render bigger images upon upload finished due to bad promise resolving

> ℹ️ As mentioned in Slack before the `uploadFile` state Action and apiImpl is pure chaos and doesn't send back any information at all is therefor totally unreliable to work with for user-feedback
I've opened a new issue for this #725

**Review by reggie7 — APPROVED** [review]

**Review by reusr1 — APPROVED** [review]
@Felix-Puetz please merge

**Pull request merged**
