### PR TITLE
Remove unused Model Factory references

### PR DESCRIPTION
**Pull request by reggie7**

### CODE REVIEW

**Comment by flx-sta** [comment]
@reggie7 there is some travis issues here

**Comment by reggie7** [comment]
> @reggie7 there is some travis issues here

Yes @Felix-Puetz, but they are related to some docker limitations that I guess @GastonGonzalez mentioned during water cooler hour once. The branch should be fine regardless.

**Comment by GastonGonzalez** [comment]
@Felix-Puetz - Ignore the Docker failures. I need to merge the docker fixes in PR #648 first.

**Review by flx-sta — APPROVED** [review]
image
image

**Review by cmrockwell — APPROVED** [review]
looks good to me

**Pull request merged**
