### PR TITLE
add a default startup message at /content/startup/index.html

### PR DESCRIPTION
**Pull request by reusr1**
this PR will need an updated peregrine-builder in order to make sure we point to the correct artifact during the startup phase

page rendered during startup: 

Screenshot from 2021-04-13 05-12-25

### CODE REVIEW

**Review by reggie7 — APPROVED** [review]

**Comment by flx-sta** [comment]
@reusr1 How can i check this?
I've tried fresh installation but it was either `404`, `403` or the login (with or without styling)

**Comment by cmrockwell** [comment]
> @reusr1 How can i check this?
> I've tried fresh installation but it was either `404`, `403` or the login (with or without styling)

Initially had the same question, but the description says "this PR will need an updated peregrine-builder"

So I built the latest peregrine-build
https://github.com/peregrine-cms/peregrine-builder

and followed the steps in the builder/README.md
https://github.com/peregrine-cms/peregrine-builder/blob/develop/builder/README.md

Upon start up, I saw the new startup screen. 

Looks pretty good imo

**Review by cmrockwell — APPROVED** [review]
New startup screen loaded with a new builder.
Approved

**Comment by reusr1** [comment]
@Felix-Puetz 

> @reusr1 How can i check this?
> I've tried fresh installation but it was either `404`, `403` or the login (with or without styling)

should be in the next develop-sling12 build - best to check with the docker image

**Comment by flx-sta** [comment]
> Initially had the same question, but the description says "this PR will need an updated peregrine-builder"
> So I built the latest peregrine-build
> https://github.com/peregrine-cms/peregrine-builder
> and followed the steps in the builder/README.md
> https://github.com/peregrine-cms/peregrine-builder/blob/develop/builder/README.md
> Upon start up, I saw the new startup screen. 
> Looks pretty good imo

I did exactly the same.
Well whatever at least you guys figured it out 👍

EDIT!: 
Tried again today. still no success :(

**Pull request merged**
