### PR TITLE
Create paths before adding permissions onto them

### PR DESCRIPTION
**Pull request by reggie7**
Fix for #735

### CODE REVIEW

**Review by reusr1 — CHANGES_REQUESTED** [review]
@reggie7 I think there is a remaining issue - after the first launch of the launcher (without peregrine) the composum console works, however, after installing peregrine the composum console is broken.

**Comment by reggie7** [comment]
@reusr1 I will need more input on the Composum issue. I've just run a test and it works both before and after installing Peregrine - without any restarts, with the following steps:
1. Make sure old `sling` and/or `launcher` folders are gone from the server instance,
2. Start Sling with `java -jar org.apache.sling.feature.launcher.jar -f com.peregrine-cms.sling.launchpad-12-SNAPSHOT-oak_tar_far.far -p sling`,
3. Check [Composum](http://localhost:8080/bin/browser.html/),
4. Install Peregrine with `mvn clean install -P autoInstallPackage`,
5. Check [Composum](http://localhost:8080/bin/browser.html/).

**Comment by reusr1** [comment]
> @reusr1 I will need more input on the Composum issue. I've just run a test and it works both before and after installing Peregrine - without any restarts, with the following steps:
> 
> 1. Make sure old `sling` and/or `launcher` folders are gone from the server instance,
> 2. Start Sling with `java -jar org.apache.sling.feature.launcher.jar -f com.peregrine-cms.sling.launchpad-12-SNAPSHOT-oak_tar_far.far -p sling`,
> 3. Check [Composum](http://localhost:8080/bin/browser.html/),
> 4. Install Peregrine with `mvn clean install -P autoInstallPackage`,
> 5. Check [Composum](http://localhost:8080/bin/browser.html/).

thanks for checking - the same steps did not work for me - will try again on my side

**Comment by reggie7** [comment]
Oh, my env was MacBook, Java 11, Chrome.

**Review by reusr1 — APPROVED** [review]
must have been me, looks good!

**Review by cmrockwell — APPROVED** [review]
Looks good! Thank you

**Pull request merged**
