### PR TITLE
selection is now cleared upon changing components (#639)

### LINKED ISSUE #639: text-selection not cleared upon selecting different component
When editing a page and you select a part of text inside one component this selection is not cleared upon changing into another one resulting in unwanted behaviour upon using the richtoolbar

### PR DESCRIPTION
**Pull request by flx-sta**
End-to-End-Test can be found here
https://github.com/Felix-Puetz/pcms-testing/blob/1baca8e9f2b761d8b847e29c8bb13954079cdc3c/src/tests/inline-editing.js#L35
https://github.com/Felix-Puetz/pcms-testing/blob/1baca8e9f2b761d8b847e29c8bb13954079cdc3c/src/tests/editor-panel-editing.js#L36

### CODE REVIEW

**Comment by reusr1** [comment]
@Felix-Puetz lets look a this PR in a sharing session - I am not sure if I like some of the ways this affects overall editing

**Comment by flx-sta** [comment]
Okay.
But just to be clear the behaviour is generally the requested one, but you just aren't sure anymore if you want to have this behaviour ?

**Review by reggie7 — APPROVED** [review]

**Comment by flx-sta** [comment]
fixed the issue of not being able to tab through anymore

**Comment by reusr1** [comment]
@Felix-Puetz I still see issues with this PR: 

- on the homepage teaser for the demo sites: click into content editable for title, click into title field in dialog, add text to dialog (text is not added in content editable) change text in subtitle (text is changed on page)

**Comment by flx-sta** [comment]
> @Felix-Puetz I still see issues with this PR:
> 
> * on the homepage teaser for the demo sites: click into content editable for title, click into title field in dialog, add text to dialog (text is not added in content editable) change text in subtitle (text is changed on page)

as discussed will this address a new issue
#679

**Pull request merged**
