### PR TITLE
PageMerge: sonar fixes + coverage

### PR DESCRIPTION
**Pull request by reggie7**

### CODE REVIEW

**Comment by reggie7** [comment]
Let me recheck it on Monday to confirm it does not break anything. I'll confirm here that this is indeed the case.

**Review by schaefa — CHANGES_REQUESTED** [review]
- The same issue with formatting as in 213
- Please make sure that you run the IT tests (go to /testing and run it with 'mvn clean instal l-P standalone') are passing. 

The rest looks fine to me

**Comment by reggie7** [comment]
Stuff fixed, I can't confirm `mvn clean install -P standalone` though - it does not work for me in `develop`. Please check if it still works on your side.

**Comment by reggie7** [comment]
Merged in [`develop-sling11`](https://github.com/reggie7/peregrine-cms/tree/develop-sling11)

**Pull request closed without merging**
