### PR TITLE
#290: fix for carousel issue

### PR DESCRIPTION
**Pull request by reusr1**
changed carousel component in example to same style as in themeclean flex

- [x] fix for v-bind:key
- [x] change from children to slides
- [x] make sure path browser works in collection

### CODE REVIEW

**Comment by ehdatheadwire** [comment]
I'm trying to review this and keep getting an error message in command: 

C:\Users\thela>docker run -it -p 9290:8080 peregrinecms/peregrinecms:pr-290
Unable to find image 'peregrinecms/peregrinecms:pr-290' locally
docker: Error response from daemon: pull access denied for peregrinecms/peregrinecms, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

Probably user error but I'm following the docker instructions so....

**Review by flx-sta — APPROVED** [review]
The functional design is now similar.

### BUT
The design does differ.
e.g.:
In example.js you cant click those bars at the bottom to switch the slide. Only the arrows on the right/left.
Also in themecleanflex the bars at the bottom are dots and the arrows on the side aren't visible

image
image

**Comment by reusr1** [comment]
@Felix-Puetz I did not change the look and feel of the carousel - only the way the data for the slides is stored, a fix for the v-for key issue in the template.vue and a fix to the path browser to point to images (was not working otherwise). - thanks for approving the PR

**Comment by reusr1** [comment]
> I'm trying to review this and keep getting an error message in command:
> 
> C:\Users\thela>docker run -it -p 9290:8080 peregrinecms/peregrinecms:pr-290
> Unable to find image 'peregrinecms/peregrinecms:pr-290' locally
> docker: Error response from daemon: pull access denied for peregrinecms/peregrinecms, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.
> 
> Probably user error but I'm following the docker instructions so....

@ehdatheadwire you would have to use

```
docker run -it -p 9812:8080 peregrinecms/peregrine-cms:pr-812
```
for this PR (it is issue 290 but pr-812 you would want to test). Also, you were missing a dash in the docker image path.

**Comment by ehdatheadwire** [comment]
> > I'm trying to review this and keep getting an error message in command:
> > C:\Users\thela>docker run -it -p 9290:8080 peregrinecms/peregrinecms:pr-290
> > Unable to find image 'peregrinecms/peregrinecms:pr-290' locally
> > docker: Error response from daemon: pull access denied for peregrinecms/peregrinecms, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> > See 'docker run --help'.
> > Probably user error but I'm following the docker instructions so....
> 
> @ehdatheadwire you would have to use
> 
> ```
> docker run -it -p 9812:8080 peregrinecms/peregrine-cms:pr-812
> ```
> 
> for this PR (it is issue 290 but pr-812 you would want to test). Also, you were missing a dash in the docker image path.

Got it. Thanks. Knew it had to be user error :) . Will review shortly.

**Review by ehdatheadwire — APPROVED** [review]
Confirm that the fix is in place and editor is able to add a slide with no errors. Also, I was able to navigate between the slides using the displayed navigation dots so no issue for me there. Approved from product/editorial perspective.

**Pull request merged**
