### PR TITLE
Pr/explorer dialog translation

### PR DESCRIPTION
**Pull request by flx-sta**
This PR provides a simple translation solution for the labels, placeholders and hints in the explorer-dialog.

It's the easiest solution to come up with for now but obviously not the best one.

_Did not test it throughly since we are currently having issue syncing our fork with the original repo. I apologize_

### CODE REVIEW

**Comment by reusr1** [comment]
@Felix-Puetz this PR also contains part of the og:tag work from another PR - can you please clean this up so it's only related to translations? thank you

**Review by reusr1 — DISMISSED** [review]
this PR contains other things than just translation (og:tag and word/character count). please remove

**Comment by flx-sta** [comment]
@reusr1 I won't remove all translations, only the ones that are specifically for og:tags.
It doesn't hurt to have too many translations I'd say..

**Comment by reusr1** [comment]
@Felix-Puetz was looking into this PR again - seems everything is pretty much merged from a translation perspective. can we close this PR?

**Comment by flx-sta** [comment]
I would like this to be merged instead of closed since an important part of translation is covered here (not in a pretties way yet, but in a working way):

The explorer dialog translation implementation in the apiImpl.js

**Pull request merged**
