### PR TITLE
feature/replicate sitemap localfs

### PR DESCRIPTION
**Pull request by GastonGonzalez**

### CODE REVIEW

**Comment by GastonGonzalez** [comment]
@reggie7 - I am putting my review on hold. Please address the following issue.

**Steps to Reproduce**
1. Log in as admin.
2. Create a new site `new_site_2`
3. Logout as admin and login as `new_site_2_user`.
4. Set `https://newsite2.cxm` as the domain in the root template
5. Click _Site Setup Replication_
6. Check your filesytem replication cache for the site map.
```
$ find staticreplication | grep sitemap.xml
``` 

**Observed Behavior**
No sitemap is generated on disk. However, if you visit http://localhost:8080/content/new_site_2/pages.sitemap.xml, the sitemap.xml file is created on disk.

```
$ find staticreplication | grep sitemap.xml
staticreplication/content/new_site_2/pages/sitemap.xml
```

I'll resume my review once this is completed,

**Comment by GastonGonzalez** [comment]
@reggie7 - I found another issue, then I'll wait for another update before starting another round of reviews.

**Steps to Reproduce**
1. Execute the steps from the previous comment.
2. Unpublish a page.
3. Visit http://localhost:8080/content/new_site_3/pages.sitemap.xml or check the sitemap.xml file in the replication cache.

**Observed Behavior**
1. Sitemap shows unpublished pages.

**Expected Behavior**
On "unpublish" (or any replication) action, the sitemap must show only the replicated pages for both `/content/site/pages.sitemap.xml` and the `sitemap.xml` file on filesystem replication cache.

The sitemap must show the replicated status of the site.

**Comment by reggie7** [comment]
@GastonGonzalez [Site Setup Replication](https://github.com/headwirecom/peregrine-cms/pull/590#issuecomment-706258406) will include the sitemap now.

**Comment by reggie7** [comment]
@GastonGonzalez [unpublish issue](https://github.com/headwirecom/peregrine-cms/pull/590#issuecomment-706264543) should be fixed now. Just please remember about the [debounce interval](http://localhost:8080/system/console/configMgr/com.peregrine.sitemap.impl.SiteMapStructureCacheImpl).

**Comment by GastonGonzalez** [comment]
Confirmed the following:
1. Sitemap reflects site state on initial replication
2. Unpublished page(s) reflected in sitemap after debounce interval (5 min)
3. New page(s) or updated page(s) are reflected in sitemap after publish and after debounce interval (5 min)
4. Basic replication regression

**Pull request merged**
