### PR TITLE
Issues/114

### PR DESCRIPTION
**Pull request by reusr1**

### CODE REVIEW

**Comment by reusr1** [comment]
@GastonGonzalez can you please review?

**Comment by GastonGonzalez** [comment]
@reusr1 ... starting review

**Comment by GastonGonzalez** [comment]
I tested this branch using the vanilla Docker build process. Immediately following a login, I am redirected to the default Sling getting started page. I will troubleshoot this later.

```
$ cd ./builddocker.sh 
$ docker run -it -p 8080:8080 peregrinecms/peregrine-cms:latest
```

**Comment by GastonGonzalez** [comment]
I confirmed that the meta tag implementation works as designed.

peregrine-issue-114-validation1

The following steps were used to test:

1. Pull and start the Peregrine stable image from DockerHub.

```
$ docker pull peregrinecms/peregrine-cms:stable
$ docker run -it -p 8080:8080 peregrinecms/peregrine-cms:stable
```

2. Deploy the latest themeclean-flex project using Maven. 

```
$ cd themeclean-flex
$ mvn clean install -P autoInstallPackage
```

3. Deploy this branch of Peregrine CMS using Maven.

```
$ cd peregrine-cms
$ git fetch
$ git checkout issues/114
$ git pull
$ mvn clean install -P autoInstallPackage
```

4. Add meta tags to the themeclean-flex index page.

5. Test OG tags using Chrome's [Open Graph Preview](https://chrome.google.com/webstore/detail/open-graph-preview/ehaigphokkgebnmdiicabhjhddkaekgh?hl=en) extension.

**Note: I am still seeing an issue when I build the Docker image from scratch in this branch.** The steps above used the stable tag of peregrine-cms in DockerHub followed by a Maven package deployment to the Docker imaging using Maven. I'll continue to test the Docker side of this as the issue may be in the Docker image?

FYI: @reusr1

**Comment by GastonGonzalez** [comment]
The Docker image works correctly with this feature once it is merged to the `developer` branch.

**Pull request merged**
