### PR TITLE
fix #254: resolve some issues all around "objects" 

### LINKED ISSUE #254: Cannot remove all items from single collection or checklist
See http://localhost:8080/content/admin/objects.html/path:/content/objects/example

Try to remove all of the items in the single collection and click okay.
The payload sent to the server shows the items successfully removed, but are re added in the response.

### PR DESCRIPTION
**Pull request by flx-sta**
- fix some issues with adding collection items (see #254 @reggie7 's mentioned error)
- fix "edit object" not switching automatically into edit mode
- fix "object info" not removing the pre-existing edit state
- adjust popup to show `askUser` modal to match patterns known from other places (unfication of ui)

fixes #254

### CODE REVIEW

**Review by reusr1 — APPROVED** [review]

**Comment by reggie7** [comment]
@KWoloszczuk could you also test this issue?

**Comment by reggie7** [comment]
@Felix-Puetz I found some edge case scenarios that don't go as expected:

- while editing an empty collection the first part of added items disappear,
- after adding a new collection the right panel still shows the previously focused object,
- edit button in the objects list does not work.

https://user-images.githubusercontent.com/5563546/109872887-5092a780-7c6d-11eb-86e3-2a37db912660.mov

Up to you to decide whether these are things for now or alternatively, for a separate ticket.

**Comment by flx-sta** [comment]
> @Felix-Puetz I found some edge case scenarios that don't go as expected:
> 
> * while editing an empty collection the first part of added items disappear,
> * after adding a new collection the right panel still shows the previously focused object,
> * edit button in the objects list does not work.
> 
>  [ video ]
> Up to you to decide whether these are things for now or alternatively, for a separate ticket.

I'll adress this in here. please mark it as "changes requested"

**Review by reggie7 — CHANGES_REQUESTED** [review]
Please fix the issues from my video comment above.

**Comment by ghost** [comment]
@Felix-Puetz : 

- fix "object info" not removing the pre-existing edit state  -  It's still not fixed. See the video. 

https://user-images.githubusercontent.com/1230506/110307386-22abbb00-7fff-11eb-99f9-7c52d848c01c.mp4

**Comment by flx-sta** [comment]
@KWoloszczuk I was able to solve your issue

----------------

@reggie7 I resolved the selection issue, but the loss of data doesn't seem to be a frontend issue.
The data is sent, but somehow lost in the BE. 
I'd say thats a new issue

**Comment by ghost** [comment]
> 
> 
> @KWoloszczuk I was able to solve your issue
> 
@Felix-Puetz Confirmed, it's working now.

**Review by ghost — APPROVED** [review]

**Comment by reggie7** [comment]
> @KWoloszczuk I was able to solve your issue
> 
> @reggie7 I resolved the selection issue, but the loss of data doesn't seem to be a frontend issue.
> The data is sent, but somehow lost in the BE.
> I'd say thats a new issue

@Felix-Puetz I moved this discussion to [254](https://github.com/headwirecom/peregrine-cms/issues/254#issuecomment-801012017) now.

**Pull request merged**
