### PR TITLE
Better range slider for forms: remove empty props in BE

### PR DESCRIPTION
**Pull request by reggie7**
Adjustment for #494
The question here is though: is it ok if we do remove all the missing props on every update? Is it sth desired for all cases? I assume yes, please let me know if that might be false.

### CODE REVIEW

**Comment by reusr1** [comment]
@reggie7 removing all properties that are not sent for save may introduce other issues and would have to be well tested throughout. The lists have a mechanism to remove children that were deleted by keeping an additional list. Maybe that is the better and safer approach here?

**Review by reusr1 — CHANGES_REQUESTED** [review]
@reggie7 @Felix-Puetz it looks like there is an edge case we are not covering in the new slider UI. In https://github.com/headwirecom/themeclean-flex/blob/d79ac8a8053fe0ee202ece93d772ff118f3ff4a0/fragments/teaservertical/model.json#L73-L81 we define a default value for the slider. When we unset the slider the UI will first show the disabled state of the component but after a refresh we show the default value again. Would love to hear your opinions about that how we should handle this case from a UX and front end/back end implementation.

**Comment by reggie7** [comment]
> @reggie7 @Felix-Puetz it looks like there is an edge case we are not covering in the new slider UI. In https://github.com/headwirecom/themeclean-flex/blob/d79ac8a8053fe0ee202ece93d772ff118f3ff4a0/fragments/teaservertical/model.json#L73-L81 we define a default value for the slider. When we unset the slider the UI will first show the disabled state of the component but after a refresh we show the default value again. Would love to hear your opinions about that how we should handle this case from a UX and front end/back end implementation.

@reusr1 I am pretty sure it has to do not with the slider, but with the [`java` model that we generate](https://github.com/headwirecom/themeclean-flex/blob/d79ac8a8053fe0ee202ece93d772ff118f3ff4a0/core/src/main/java/com/themecleanflex/models/TeaserverticalModel.java#L604-L606) based on [`model.json`](https://github.com/headwirecom/themeclean-flex/blob/d79ac8a8053fe0ee202ece93d772ff118f3ff4a0/fragments/teaservertical/model.json#L73-L81):
```
@Inject
@Default(values ="100")
private String textwidth;
```
I'd say the behavior is correct then since the slider simply follows the data that it is fed with. And we should rethink the BE, what do you guys think?

**Comment by flx-sta** [comment]
@reggie7 so you are saying that the java-object grabs the default-value when the value is null?
If that is the case I'd say you are right

**Comment by reusr1** [comment]
I think the problem is in the UX of the slider. @Felix-Puetz if a default value exists and we switch to the off state we should actually move the slider to the default value as well?

**Comment by flx-sta** [comment]
@reusr1 assuming the default value exists on the slider it would be a nice visual feedback cherry

**Comment by reggie7** [comment]
@reusr1 @Felix-Puetz let me guys know if we cover the case below and who (me or @Felix-Puetz) would take care of this.

> I think the problem is in the UX of the slider. @Felix-Puetz if a default value exists and we switch to the off state we should actually move the slider to the default value as well?

**Pull request merged**
