### PR TITLE
Range Slider's default state enhancements #693

### LINKED ISSUE #693: Range Slider should handle the default state better
due to PR https://github.com/headwirecom/peregrine-cms/pull/688#issuecomment-753969660 we realized the range slider UX should also handle the default value a bit better.

### PR DESCRIPTION
**Pull request by flx-sta**
image

closes #693

### CODE REVIEW

**Comment by reggie7** [comment]
There is the following issue here to solve:

https://user-images.githubusercontent.com/5563546/104037917-25438d00-51d5-11eb-8341-9da0270a0880.mov

After a series of 3 clicks (range, button, button) we get an unwanted label.

**Comment by flx-sta** [comment]
Wow. That's an impressively crazy bug.
I guess will write a test for that including it into your `range-slider.js`

**Comment by reggie7** [comment]
> Wow. That's an impressively crazy bug.
> I guess will write a test for that including it into your `range-slider.js`

@Felix-Puetz sure, grab my changes to have the PRs combined [as we've discussed](https://github.com/headwirecom/peregrine-cms/pull/700#issuecomment-757025591).

**Comment by flx-sta** [comment]
> There is the following issue here to solve:
> 
>  [[video]] 
> After a series of 3 clicks (range, button, button) we get an unwanted label.

fixed that in the last 2 commits

was a bit tricky but i figured it out..

**Comment by Felix-Puetz** [comment]
closes #688

**Comment by reggie7** [comment]
Ok, confirmed, the bug is fixed, thank you.

**Review by reggie7 — APPROVED** [review]

**Review by ehdatheadwire — APPROVED** [review]
Confirmed that the default state moves the slider to the 50 value and can be toggled by author. 

https://user-images.githubusercontent.com/51373617/105427981-3cd23b00-5c03-11eb-891b-ee05099e5aef.mp4

**Pull request merged**
