### PR TITLE
#97: new modal for the richtext editor for links and images

### PR DESCRIPTION
**Pull request by reusr1**

### CODE REVIEW

**Comment by reusr1** [comment]
@bkheadwire please review

**Comment by bkheadwire** [comment]
There's a couple of issues:
1. Inserting a link by selecting a page in the content structure with the pathbrowser fails: https://youtu.be/s3R_cBx8Ua0. This appears to be related to the next issue...
2. Inserting a link using the link tab in the pathbrowser fails silently if you don't add a title.
3. Changing an existing link to a different path causes the text of the link to disappear. https://youtu.be/0skI6aerax8
4. If you insert an image and then try to choose a different image to replace it, the change is shown in the editor but not reflected in the content. Saving the edit does not persist the change. https://youtu.be/fG7rIQlLMig

**Comment by dna113p** [comment]
@bkheadwire I have updated issues/97 and it should fix all of the things in your last comment.

**Comment by reusr1** [comment]
@dna113p a link should always be inserted with .html at the end of the url and when editing a link the path browser should show the currently selected link. Same goes for editing an image

the path browser also has an issue with the footer - the path of the selected asset should fill the space on the left of the cancel/select buttons

**Comment by bkheadwire** [comment]
All the issues I raised before are now fixed.

**Pull request merged**
